vim.keymap.set('n', '<S-r>', ':GoRun<CR>' , opt)
vim.keymap.set('n', '<S-t>', ':GoTest<CR>' , opt)
vim.keymap.set('n', '<F2>', ':GoRun<CR>' , opt)
vim.keymap.set('n', '<F3>', ':GoDebugStart<CR>' , opt)
vim.keymap.set('n', '<F4>', ':GoDebugStop<CR>' , opt)
